baseURL = "https://train404creative.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Cakewalk Design"
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[[menu.main]]
URL = "services"
name = "Blog"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[params]
address = "#300-34334 Forrest Terrace  |  Abbotsford, B.C., Canada  |  V2S 1G7"
author = "James Davenport"
copyright = "Copyright &copy; 2020 Cakewalk Design"
description = "Cakewalk Design, Custom Websites for Wineries"
email = "hello@cakewalkdesign.com"
google_analytics_id = ""
home = "Home"
logo = "/images/cakewalk-logo.png"
phone = "1-877-667-6484"
theme_color = "#29acd8"
[params.contact]
enable = true
form_action = "#"
[params.cookies]
enable = true
expire_days = 2
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[params.preloader]
enable = false
preloader = "images/preloader.gif"
[[params.social]]
URL = "https://www.facebook.com/cakewalkdesign"
icon = "ti-facebook"
[[params.social]]
URL = "https://twitter.com/cakewalkdesign"
icon = "ti-twitter-alt"
